### PR TITLE
Update for Web Server

### PR DESCRIPTION
**Pull request by Balferian**
Fixes https://github.com/rathena/FluxCP/issues/315 .

Changes proposed in this Pull Request:
- [x]  Allowed to use external db for web server for guild icons.
- [x]  Usage of "EmblemUseWebservice" was removed from modules.
- [x]  Added support for gif with transparent layer.
- [ ] Find the way to convert rgb(255, 0, 255) mask to transparent layer for animated GIF emblem.

https://user-images.githubusercontent.com/16213511/191065655-3e394127-76e6-4131-80b3-ebeb0a5140fb.mp4

### CODE REVIEW

**Comment by ecdarreola** [comment]
Transparent gif with rgb(255, 0, 255) as some fill are displaying as is? Is this intended?

**Comment by Daegaladh** [comment]
The only way to change the magenta background into transparent and keep the animation I can think of is using imagemagick

**Comment by mazvi** [comment]
We don't have to worry about transparency :) no problem not being transparent on the website :D

**Comment by Balferian** [comment]
> The only way to change the magenta background into transparent and keep the animation I can think of is using imagemagick

imagick package is not included by default in php, users may experience problems because of this (not all hosts allow to install packages for php), so I don't want to use imagemagick now.
If there is no other way to process GIFs, then we will return to this option (imagemagick) and make it optional.

**Comment by Daegaladh** [comment]
Well, php-gd is also an extension and we use it anyway

**Comment by Pokye** [comment]
Any prediction on when this PR will merge? xD

**Comment by mazvi** [comment]
> Any prediction on when this PR will merge? xD

My prediction is February 2024

**Pull request merged**
