### PR TITLE
deadcode: fix "Commented code should not be committed" from sensiolabs insight

### PR DESCRIPTION
**Pull request by hurtsky**
cleanup commented code

### CODE REVIEW

**Comment by Akkarinage** [comment]
The markdown lib and phpmailer don't need to be touched, they'll get an update so your changes would be overwritten anyway.

**Comment by hurtsky** [comment]
i also already thought like that, but i just want to silence those warning. and it will be overwritten again after you update it. 👍

**Comment by Akkarinage** [comment]
I need you to revert the changes you made to the markdown and phpmailer libraries before i can merge this PR. I can't remove markdown nor update the mailer while these changes are still here.

If it's easier, cancel the PR and just submit a new one with the commented code removal.

**Comment by hurtsky** [comment]
okay, i close the pull request and make a new one.

**Pull request closed without merging**
