### PR TITLE
Add Divine-Pride integration (items and monster images)

### PR DESCRIPTION
**Pull request by Balferian**
This update dowload monsters and items images from https://www.divine-pride.net if it's not exist.
image

### CODE REVIEW

**Comment by RadianFord** [comment]
Great job @Balferian !!

**Comment by Akkarinage** [comment]
I assume you've spoken to Dia about pulling images from his website? If we merge this into FluxCP his bandwidth and file requests will skyrocket.

**Comment by Balferian** [comment]
> I assume you've spoken to Dia about pulling images from his website? If we merge this into FluxCP his bandwidth and file requests will skyrocket.

Yes, I asked him about it before i make this pull.

**Comment by mazvi** [comment]
> 
> 
> I assume you've spoken to Dia about pulling images from his website? If we merge this into FluxCP his bandwidth and file requests will skyrocket.

hahaha

**Comment by Everade** [comment]
Works great.
The only downside is that it also downloads an empty image if the id doesn't exist.

Would be great if that could be prevented.

**Comment by Everade** [comment]
@Akkarinage No it's really bad because same goes for all official items. Once divine pride adds images, you will miss out on them due to the empty images that have been downloaded already.
This should be adressed eventualy.

**Pull request merged**
