### PR TITLE
Theme Bootstrap: Fixed a ReferenceError of jQuery

### PR DESCRIPTION
**Pull request by kraaijmakers**
which got accessed before the minified jQuery itself got imported.

I hope I did this right, this is my first time using Github like this.

### CODE REVIEW

**Comment by kraaijmakers** [comment]
Well, in the footer.php there is a <script type="text/javascript"> which tries to communicate with jQuery using $(document). Since there is no $ defined in default JavaScript it errored at Chrome Developer Console, the reference they tried to make was to jQuery on line 41. But since the jQuery.min.js gets called after the block I just moved it upwards before the block, and gone was the error. so tl;dr:

**Comment by Akkarinage** [comment]
This could potentially be a controversial change, given that bootstrap itself recommends that the JS files are loaded just before the end of the page.. so maybe we should just move the offending code to underneath the line that loaded jquery originally?

**Comment by kraaijmakers** [comment]
OK wait, so you mean the scripts which dont use the jQuery should be loaded before jQuery get's loaded, then jQuery, then the script referencing to jQuery?

**Comment by Akkarinage** [comment]
Not quite - I mean that _all_ the JS should be loaded from the end of the page. In theory we should move everything to the footer, so the jquery lib is loaded first, then bootstrap, then everything else fluxcp related, then the `</body>` tag. 

In reality though, this is bound to break other functions (if there are any) placed there by user.

I'm on the fence with this one.

**Comment by kraaijmakers** [comment]
Oh, I think you misunderstood, since the only file I changed was theme/bootstrap/footer.php so nothing has changed to the Control panel at all, except for the order the scripts get loaded. (in footer.php)

**Comment by cydh** [comment]
I guess this is what @kraaijmakers meant
the `$` is not recognized because the jquery wasn't loaded

image

pointing to
image

**Comment by kraaijmakers** [comment]
That is indeed what I meant. Sorry if I was unclear. I don't use git normally. Also first time I tried contributing haha :)

**Pull request merged**
